---
storyboard: openstack/ironic-prometheus-exporter
release-model: cycle-with-intermediary
stable-branch-type: std-with-versions
team: ironic
type: other
repository-settings:
  openstack/ironic-prometheus-exporter: {}
releases:
  - version: 3.1.0
    projects:
      - repo: openstack/ironic-prometheus-exporter
        hash: ed207dc3cd362642568e0d87cdb1239ca1d11bbd
branches:
  - name: stable/yoga
    location: 3.1.0
