---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 9.7.0
    projects:
      - repo: openstack/oslo.config
        hash: 82552116f827030ce1e493506fe83ef71656e447
