---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - projects:
      - hash: 0bc22839b09fcd7ae2de4f7fe5d63ac055fd0a78
        repo: openstack/oslo.config
    version: 6.9.0
  - projects:
      - hash: 9513d26b47c59a3c97aefab46c3e5a40d953e286
        repo: openstack/oslo.config
    version: 6.10.0
  - projects:
      - hash: dea9af2fe91e3abe6ca88ea8739cff023191abb9
        repo: openstack/oslo.config
    version: 6.11.0
  - version: 6.11.1
    projects:
      - repo: openstack/oslo.config
        hash: c4d8fa7b88f3d952b7faabd89dc22123a1cb7e03
  - version: 6.11.2
    projects:
      - repo: openstack/oslo.config
        hash: 22c286c63b15b6f0acf6f696b98226a9257bf745
  - version: 6.11.3
    projects:
      - repo: openstack/oslo.config
        hash: 9b1ccea642f0769cb6c49bf814ddab62ca5d8180
  - version: train-em
    projects:
      - repo: openstack/oslo.config
        hash: 9b1ccea642f0769cb6c49bf814ddab62ca5d8180
branches:
  - name: stable/train
    location: 6.11.1
release-notes: https://docs.openstack.org/releasenotes/oslo.config/train.html
