---
launchpad: ironic-prometheus-exporter
release-model: cycle-with-intermediary
stable-branch-type: std-with-versions
team: ironic
type: other
repository-settings:
  openstack/ironic-prometheus-exporter: {}
releases:
  - version: 4.7.0
    projects:
      - repo: openstack/ironic-prometheus-exporter
        hash: 6cd0a5a53f3893857c31d01006fcb51102536b7b
  - version: 4.8.0
    projects:
      - repo: openstack/ironic-prometheus-exporter
        hash: d827b34e3849da4e7e6e898791df79a0f689c7e8
branches:
  - name: stable/2026.1
    location: 4.8.0
