---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 9.1.0
    projects:
      - repo: openstack/oslo.config
        hash: 84478d83f87e9993625044de5cd8b4a18dfcaf5d
  - version: 9.1.1
    projects:
      - repo: openstack/oslo.config
        hash: 515daab81acccbea4015afc5c3c3316d88903a10
