---
branches:
  - location: 4.11.0
    name: stable/pike
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
release-notes: https://docs.openstack.org/releasenotes/oslo.config/pike.html
releases:
  - projects:
      - hash: e53c79ebbb0f31db3bdf64760551f357b50c08a7
        repo: openstack/oslo.config
    version: 3.23.0
  - projects:
      - hash: efb287a94645b15b634e8c344352696ff85c219f
        repo: openstack/oslo.config
    version: 3.24.0
  - projects:
      - hash: 4cc7c6cb9bd96c986680241bbf2d3d454bcba246
        repo: openstack/oslo.config
    version: 4.0.0
  - projects:
      - hash: 12fd34b963f6efa1bd8afd8ce06de33c90135f6d
        repo: openstack/oslo.config
    version: 4.1.0
  - projects:
      - hash: 3290830993094d8bfebaabd499ffd825bffdb3a6
        repo: openstack/oslo.config
    version: 4.1.1
  - projects:
      - hash: f0a915f5969a815b6469f56b88f9e346e394a733
        repo: openstack/oslo.config
    version: 4.2.0
  - projects:
      - hash: d32af197a75dfae5670e6fe75f1bdb2626c75a88
        repo: openstack/oslo.config
    version: 4.3.0
  - projects:
      - hash: 010e6be5f9ebf4808e63a328bd29128b9d41155e
        repo: openstack/oslo.config
    version: 4.4.0
  - projects:
      - hash: 6e420e9de5958dd27e6f1a38ef9bc578dde435a2
        repo: openstack/oslo.config
    version: 4.5.0
  - projects:
      - hash: 83d69f888f6c9bb89ae1e02e21b85422183efb41
        repo: openstack/oslo.config
    version: 4.6.0
  - projects:
      - hash: 4848dfece9167cc310897d03df0263de4853572c
        repo: openstack/oslo.config
    version: 4.7.0
  - projects:
      - hash: 938077097f3bfbaac621909774f405b101236b48
        repo: openstack/oslo.config
    version: 4.8.0
  - projects:
      - hash: 608a15ea61ae846c07624e869c16d37781c2a8ce
        repo: openstack/oslo.config
    version: 4.9.0
  - projects:
      - hash: 11c39ac065c36259af6ff688abe3383fab7b2f1a
        repo: openstack/oslo.config
    version: 4.10.0
  - projects:
      - hash: dfc70fa88e01b8c6ca1ab15a4b80bd33e87ced85
        repo: openstack/oslo.config
    version: 4.11.0
  - projects:
      - hash: fb0738974824af6e1bc7d9fdf32a7c1d3ebf65fb
        repo: openstack/oslo.config
    version: 4.11.1
  - projects:
      - hash: b0436f0c0950bb49726154a616cbbc4d7aeaf21e
        repo: openstack/oslo.config
    version: 4.11.2
  - projects:
      - hash: b0436f0c0950bb49726154a616cbbc4d7aeaf21e
        repo: openstack/oslo.config
    version: pike-em
  - version: pike-eol
    projects:
      - repo: openstack/oslo.config
        hash: 1f76ae18ba71a8446ca9ac3bb1e4430fc5a29f54
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
