---
launchpad: openstack-requirements
team: requirements
type: other
include-pypi-link: true
release-model: cycle-with-intermediary
stable-branch-type: tagless
branches:
  - location:
      openstack/requirements: b93ebaf5c5295ff29d01e374f3720bc8ea3175f6
    name: stable/pike
releases:
  - version: 1.1.0
    projects:
      - repo: openstack/requirements
        hash: f5ce4279b968d04674ea32052cfe83f9a1aaddb8
        tarball-base: openstack_requirements
  - version: pike-eol
    projects:
      - repo: openstack/requirements
        hash: e0cb0c20b07a14a6ef1fd60f36c4e95f2964dc21
repository-settings:
  openstack/requirements: {}
