---
launchpad: os-apply-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: other
releases:
  - projects:
      - hash: 8db1c024eee51cc994e19ec44b6d3a141d070ec5
        repo: openstack/os-apply-config
    version: 8.0.0
  - projects:
      - hash: 8dbeb75d798869fe186d1d916314b2362b402c4e
        repo: openstack/os-apply-config
    version: 8.1.0
  - projects:
      - hash: 775d6dc6ddc16c31566b18b5054203c79b00e8d1
        repo: openstack/os-apply-config
    version: 8.2.0
  - projects:
      - hash: 81baf73ae89a7dd5a15869986ea3b8adf5187680
        repo: openstack/os-apply-config
    version: 8.3.0
  - projects:
      - hash: be699ba6e0dc29c767ed6d8dc3643950b07da292
        repo: openstack/os-apply-config
    version: 8.3.1
  - projects:
      - hash: ad29f1d44923d12c8c91e6389fda6535653dac2c
        repo: openstack/os-apply-config
    version: 8.3.2
  - version: queens-em
    projects:
      - repo: openstack/os-apply-config
        hash: ad29f1d44923d12c8c91e6389fda6535653dac2c
  - version: queens-eol
    projects:
      - repo: openstack/os-apply-config
        hash: b8687b3a6b712bebfbd62452d6f27e0241f91b95
repository-settings:
  openstack/os-apply-config: {}
branches:
  - location: 8.3.0
    name: stable/queens
