---
include-pypi-link: true
launchpad: os-client-config
release-model: cycle-with-intermediary
release-notes: https://docs.openstack.org/releasenotes/os-client-config/queens.html
team: OpenStackSDK
type: library
releases:
  - projects:
      - hash: ed71a5994f747951c737b16e300ed9dec54a4750
        repo: openstack/os-client-config
    version: 1.29.0
  - version: queens-em
    projects:
      - repo: openstack/os-client-config
        hash: ed71a5994f747951c737b16e300ed9dec54a4750
  - version: queens-eol
    projects:
      - repo: openstack/os-client-config
        hash: 4796f993c6dc5c988c4fd05ba49fccbe3ba12917
branches:
  - name: stable/queens
    location: 1.29.0
repository-settings:
  openstack/os-client-config: {}
