---
launchpad: os-collect-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: other
releases:
  - projects:
      - hash: f7f49448a5a0c54ac4dbf56b8809ee1f365e038f
        repo: openstack/os-collect-config
    version: 8.0.0
  - projects:
      - hash: fd530b4294dc94ae64dfe0bdc70c628d0402974e
        repo: openstack/os-collect-config
    version: 8.1.0
  - projects:
      - hash: 5f2835e7a049d128623fa07ba1d9b103284348f8
        repo: openstack/os-collect-config
    version: 8.2.0
  - projects:
      - hash: 4e48cfa2cc5b373e1660972a9b7f412c3a4697de
        repo: openstack/os-collect-config
    version: 8.3.0
  - projects:
      - hash: cf2d08c7a5ed428c3db0c76379b4cf6a5b791055
        repo: openstack/os-collect-config
    version: 8.3.1
  - version: queens-em
    projects:
      - repo: openstack/os-collect-config
        hash: cf2d08c7a5ed428c3db0c76379b4cf6a5b791055
  - version: queens-eol
    projects:
      - repo: openstack/os-collect-config
        hash: 443df6379eea51a631bac659fca271ab84ba17b1
repository-settings:
  openstack/os-collect-config: {}
branches:
  - location: 8.3.0
    name: stable/queens
