---
launchpad: os-net-config
release-model: cycle-with-intermediary
release-type: python-pypi
team: tripleo
type: other
releases:
  - projects:
      - hash: 44f3957b9ef1fa15797520ee1f0e3fc42e0c2b27
        repo: openstack/os-net-config
    version: 8.0.0
  - projects:
      - hash: bb7d8296d7a27ed2ddd9702b56c1fb0d6ae37b6e
        repo: openstack/os-net-config
    version: 8.1.0
  - projects:
      - hash: 123ddf0df4e0a5d95952c47dc9fe1021427a4209
        repo: openstack/os-net-config
    version: 8.2.0
  - projects:
      - hash: 108941640d74268eb932386e32f7e6df40c74180
        repo: openstack/os-net-config
    version: 8.3.0
  - projects:
      - hash: e699c687aaed82b4750d5a8b9fe5e033f846e102
        repo: openstack/os-net-config
    version: 8.4.0
  - projects:
      - hash: 08a0f081bf627ef09b934b2cc1dc66e172a1dbd4
        repo: openstack/os-net-config
    version: 8.4.1
  - projects:
      - hash: e78b09635c424b62b22ee7f19e36abfc71348b21
        repo: openstack/os-net-config
    version: 8.4.2
  - projects:
      - hash: 9084bb5e5788815158d536a13e2992715829a292
        repo: openstack/os-net-config
    version: 8.4.3
  - projects:
      - hash: ebf14d2f54a96829734d3d25c0ecfff2b01d630b
        repo: openstack/os-net-config
    version: 8.4.4
  - projects:
      - hash: 1e3432166b7b8403f3fdf899b4cf2c4a2c40f10b
        repo: openstack/os-net-config
    version: 8.5.0
  - version: 8.5.1
    projects:
      - repo: openstack/os-net-config
        hash: 2a374db9847b92cc3f9da9be20a614932d9dd997
  - version: queens-em
    projects:
      - repo: openstack/os-net-config
        hash: 2a374db9847b92cc3f9da9be20a614932d9dd997
  - version: queens-eol
    projects:
      - repo: openstack/os-net-config
        hash: 99b56aa883ca0deac3150115af0db90f2ffe462e
repository-settings:
  openstack/os-net-config: {}
branches:
  - location: 8.3.0
    name: stable/queens
release-notes: https://docs.openstack.org/releasenotes/os-net-config/queens.html
