---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
releases:
  - version: 4.12.0
    projects:
      - repo: openstack/oslo.config
        hash: 7fde851f8dc7ab0a4b796c2bba0e166f226e7674
  - projects:
      - hash: e6749d3208cffd7693353385f92865d9ac737623
        repo: openstack/oslo.config
    version: 4.13.0
  - projects:
      - hash: 0cce0be52abddc670f8d7451f240481eaa9fe208
        repo: openstack/oslo.config
    version: 4.13.1
  - projects:
      - hash: 36aded18660fc4d515aaabfc7bf1afbfb65e6411
        repo: openstack/oslo.config
    version: 4.13.2
  - projects:
      - hash: a3e7f8aa172f68bafd973206c9529773bbc16672
        repo: openstack/oslo.config
    version: 5.0.0
  - projects:
      - hash: eb6ff02d4b863bad7bf04a5a78d501450e8c0b93
        repo: openstack/oslo.config
    version: 5.1.0
  - projects:
      - hash: 557861692fffb9af032caccc37c84a0189ebbf83
        repo: openstack/oslo.config
    version: 5.2.0
  - projects:
      - hash: 6056677f35347cd82c12fc9020b02ef142dbe289
        repo: openstack/oslo.config
    version: 5.2.1
  - version: queens-em
    projects:
      - repo: openstack/oslo.config
        hash: 6056677f35347cd82c12fc9020b02ef142dbe289
  - version: queens-eol
    projects:
      - repo: openstack/oslo.config
        hash: 31c11ab4289efa1a91835f3daa928fe927ac4276
branches:
  - name: stable/queens
    location: 5.2.0
release-notes: https://docs.openstack.org/releasenotes/oslo.config/queens.html
repository-settings:
  openstack/oslo.config: {}
