---
launchpad: ironic-prometheus-exporter
release-model: cycle-with-intermediary
stable-branch-type: std-with-versions
team: ironic
type: other
repository-settings:
  openstack/ironic-prometheus-exporter: {}
releases:
  - version: 4.4.0
    projects:
      - repo: openstack/ironic-prometheus-exporter
        hash: ff726aca1a9d9a69977bc6d48be652a26ff235fe
branches:
  - name: stable/2024.2
    location: 4.4.0
