---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 9.5.0
    projects:
      - repo: openstack/oslo.config
        hash: bc7cc773d1bb16cc4b6ffe1dc1827536c5707183
  - version: 9.6.0
    projects:
      - repo: openstack/oslo.config
        hash: beb7b6ce2b8a36376324c300328e678bd02ae63a
branches:
  - name: stable/2024.2
    location: 9.6.0
release-notes: https://docs.openstack.org/releasenotes/oslo.config/2024.2.html
