---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 9.0.0
    projects:
      - repo: openstack/oslo.config
        hash: 9eaae044534cbe015217019781c4c0d97f0402df
branches:
  - name: stable/zed
    location: 9.0.0
release-notes: https://docs.openstack.org/releasenotes/oslo.config/zed.html
