---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 8.1.0
    projects:
      - repo: openstack/oslo.config
        hash: 2b698facfdb175b5d83026af85f55b8c3dc6d3e0
  - version: 8.2.0
    projects:
      - repo: openstack/oslo.config
        hash: 04d5280c3d90ca6f8d495c945143c5f2858024a1
  - version: 8.3.0
    projects:
      - repo: openstack/oslo.config
        hash: 392922aa333f9777f98e7ce61ad46f69cd9ac455
  - version: 8.3.1
    projects:
      - repo: openstack/oslo.config
        hash: a2652b3584da06e4c4ebe96261672309b01c1122
  - version: 8.3.2
    projects:
      - repo: openstack/oslo.config
        hash: fcb88941e39a31e3ef6c5a930063da419431a7f6
  - version: 8.3.3
    projects:
      - repo: openstack/oslo.config
        hash: d9129d8af7fb545c55a003e200e4a93931f79701
  - version: 8.3.4
    projects:
      - repo: openstack/oslo.config
        hash: 0950f82ec59e1b4a2af66b5c5940a651a5cb574f
  - version: victoria-em
    projects:
      - repo: openstack/oslo.config
        hash: 0950f82ec59e1b4a2af66b5c5940a651a5cb574f
  - version: victoria-eom
    projects:
      - repo: openstack/oslo.config
        hash: 0950f82ec59e1b4a2af66b5c5940a651a5cb574f
branches:
  - name: stable/victoria
    location: 8.3.2
  - name: unmaintained/victoria
    location: victoria-eom
release-notes: https://docs.openstack.org/releasenotes/oslo.config/victoria.html
