---
include-pypi-link: true
storyboard: openstack/os-client-config
release-model: cycle-with-intermediary
team: OpenStackSDK
type: library
repository-settings:
  openstack/os-client-config: {}
releases:
  - version: 2.0.0
    projects:
      - repo: openstack/os-client-config
        hash: efd56a806e5d1ffad3dc8f31116c7e045b81ad04
  - version: 2.1.0
    projects:
      - repo: openstack/os-client-config
        hash: bc96c23a9c44cee8f54d7349b288a406cec3f10a
  - version: ussuri-em
    projects:
      - repo: openstack/os-client-config
        hash: bc96c23a9c44cee8f54d7349b288a406cec3f10a
  - version: ussuri-eol
    projects:
      - repo: openstack/os-client-config
        hash: 7868a144a48a17648f4ceb712932b63c2d76e457
branches:
  - name: stable/ussuri
    location: 2.1.0
release-notes:
  https://docs.openstack.org/releasenotes/os-client-config/ussuri.html
