---
launchpad: os-client-config
team: OpenStackSDK
release-notes: https://docs.openstack.org/releasenotes/os-client-config/ocata.html
type: library
release-model: cycle-with-intermediary
include-pypi-link: true
branches:
  - name: stable/ocata
    location: 1.26.0
releases:
  - version: 1.22.0
    projects:
      - repo: openstack/os-client-config
        hash: 6c252384c2cff4eef68d93e33d9bf81c9b768d38
  - version: 1.23.0
    projects:
      - repo: openstack/os-client-config
        hash: ba57e4f509f3ba8768027b29e9233252148f1eef
  - version: 1.24.0
    projects:
      - repo: openstack/os-client-config
        hash: e2a593d917533424c6de39774afb8566d4f81db2
  - version: 1.25.0
    projects:
      - repo: openstack/os-client-config
        hash: 90c3d001b6ceb7a7b17bc3c4906c2b4746e24d44
  - version: 1.26.0
    projects:
      - repo: openstack/os-client-config
        hash: 3c47e251c978cf9c5e393f032c0c70d67c1dcb00
  - projects:
      - hash: 3c47e251c978cf9c5e393f032c0c70d67c1dcb00
        repo: openstack/os-client-config
    version: ocata-em
  - version: ocata-eol
    projects:
      - repo: openstack/os-client-config
        hash: 102fabfe548ac98b9f5898c424d8a32ba46a9978
repository-settings:
  openstack/os-client-config: {}
