---
launchpad: os-cloud-config
team: tripleo
type: other
release-model: cycle-with-milestones
repository-settings:
  openstack/os-cloud-config:
    flags:
      - no-artifact-build-job
      - retired
branches:
  - name: stable/ocata
    location: 6.0.0.0rc1
releases:
  - version: 6.0.0.0b1
    projects:
      - repo: openstack/os-cloud-config
        hash: f206fd88e4885e5c945a7b726971c99da0b09d11
  - version: 6.0.0.0b2
    projects:
      - repo: openstack/os-cloud-config
        hash: 9b0918551c68083e3226341cb97ddd03aa5229e6
  - version: 6.0.0.0rc1
    projects:
      - repo: openstack/os-cloud-config
        hash: 8cbab5ceeeae52363ea8c5188b8a0604cc420e34
  - version: 6.0.0
    diff-start: 5.0.0
    projects:
      - repo: openstack/os-cloud-config
        hash: 8cbab5ceeeae52363ea8c5188b8a0604cc420e34
  - projects:
      - hash: 8cbab5ceeeae52363ea8c5188b8a0604cc420e34
        repo: openstack/os-cloud-config
    version: ocata-em
  - projects:
      - hash: 185bed9d6ae89e0439d17b4b289dee5d8a6d73a7
        repo: openstack/os-cloud-config
    version: ocata-eol
