---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 9.2.0
    projects:
      - repo: openstack/oslo.config
        hash: 28187da6d7b8eae39208e7cefbbc7da32ec3d3be
  - version: 2023.2-eol
    projects:
      - repo: openstack/oslo.config
        hash: f1ecdedf9048bd7925dcc688d648c98ed1744da8
branches:
  - name: stable/2023.2
    location: 9.2.0
release-notes: https://docs.openstack.org/releasenotes/oslo.config/2023.2.html
