---
include-pypi-link: true
launchpad: os-client-config
release-model: cycle-with-intermediary
team: OpenStackSDK
type: library
releases:
  - projects:
      - hash: 74fc34a8f07036c4944c22da7a5c02a1ccdfdb71
        repo: openstack/os-client-config
    version: 1.32.0
  - version: stein-em
    projects:
      - repo: openstack/os-client-config
        hash: 74fc34a8f07036c4944c22da7a5c02a1ccdfdb71
  - version: stein-eol
    projects:
      - repo: openstack/os-client-config
        hash: af9e8837c30a1e90ead7a83a6ac3f1a319126ae6
repository-settings:
  openstack/os-client-config: {}
branches:
  - location: 1.32.0
    name: stable/stein
release-notes: 
  https://docs.openstack.org/releasenotes/os-client-config/stein.html
