---
launchpad: openstack-requirements
team: requirements
type: other
include-pypi-link: true
release-model: cycle-with-intermediary
stable-branch-type: tagless
repository-settings:
  openstack/requirements: {}
branches:
  - name: stable/stein
    location:
      openstack/requirements: 898666b755fe209d391a256d64e48bb22c1a7d25
releases:
  - version: stein-eol
    projects:
      - repo: openstack/requirements
        hash: 8ca8e28da38bbbc9f66c683f2ad71f34cdc6337a
