---
launchpad: os-refresh-config
release-type: python-pypi
team: tripleo
type: other
repository-settings:
  openstack/os-refresh-config: {}
releases:
  - version: 13.0.0
    projects:
      - repo: openstack/os-refresh-config
        hash: 754bb751e6728aafa680111a6fab3013609654cc
  - version: 13.0.1
    projects:
      - repo: openstack/os-refresh-config
        hash: 197972b69234f6e3a7c032c79acecf523d7cb96c
  - version: 13.1.0
    projects:
      - repo: openstack/os-refresh-config
        hash: 5bb536c13bbefee705fda44ca96ccc957625d186
