---
launchpad: ironic-prometheus-exporter
release-model: cycle-with-intermediary
stable-branch-type: std-with-versions
team: ironic
type: other
repository-settings:
  openstack/ironic-prometheus-exporter: {}
releases:
  - version: 4.9.0
    projects:
      - repo: openstack/ironic-prometheus-exporter
        hash: f3d2a9cdfe385c835ed707962f9c81f9fc730f7b
