---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 10.4.0
    projects:
      - repo: openstack/oslo.config
        hash: 4317c230dd7289229148baf7c50309cdbf4e0311
  - version: 10.5.0
    projects:
      - repo: openstack/oslo.config
        hash: 183a7ab1cf20e0bd6cc48c05677ea02c945b8794
  - version: 10.6.0
    projects:
      - repo: openstack/oslo.config
        hash: e14826601fd72d975d81c040ffbdbdedb5750726
