---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 9.3.0
    projects:
      - repo: openstack/oslo.config
        hash: 2930db4892e06e97c441d68574bac0930175a16a
  - version: 9.4.0
    projects:
      - repo: openstack/oslo.config
        hash: 882adf8e4d0685ea3404067fa38066abec9bd5f6
  - version: 9.4.1
    projects:
      - repo: openstack/oslo.config
        hash: 144d02a316c2f32105bceb686dd51ee6983496d3
  - version: 2024.1-eom
    projects:
      - repo: openstack/oslo.config
        hash: 144d02a316c2f32105bceb686dd51ee6983496d3
branches:
  - name: stable/2024.1
    location: 9.4.0
  - name: unmaintained/2024.1
    location: 2024.1-eom
release-notes:
  https://docs.openstack.org/releasenotes/oslo.config/2024.1.html
