---
include-pypi-link: true
launchpad: oslo.config
release-model: cycle-with-intermediary
team: oslo
type: library
repository-settings:
  openstack/oslo.config: {}
releases:
  - version: 9.3.0
    projects:
      - repo: openstack/oslo.config
        hash: 2930db4892e06e97c441d68574bac0930175a16a
  - version: 9.4.0
    projects:
      - repo: openstack/oslo.config
        hash: 882adf8e4d0685ea3404067fa38066abec9bd5f6
